package vistas;

import DAOs.DAO_Categorias;
import javax.swing.JOptionPane;
import modelo.Categorias;

public class vAgregarCategoria extends javax.swing.JFrame {

    public vAgregarCategoria() {
        initComponents();
        this.daoCategorias = new DAO_Categorias();

    }
    private DAO_Categorias daoCategorias;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgregar_categoria_nombre = new javax.swing.JLabel();
        btnAgregar_categoria_agregar = new javax.swing.JButton();
        txtAgregar_categoria_nombre = new javax.swing.JTextField();
        lblAgregar_categoria = new javax.swing.JLabel();
        lblAgregar_categoria_descripcion = new javax.swing.JLabel();
        txtAgregar_categoria_descripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(319, 365));

        lblAgregar_categoria_nombre.setText("Nombre:");

        btnAgregar_categoria_agregar.setText("Agregar");
        btnAgregar_categoria_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_categoria_agregarActionPerformed(evt);
            }
        });

        lblAgregar_categoria.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAgregar_categoria.setText("Agregar Categoria");

        lblAgregar_categoria_descripcion.setText("Descripcion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregar_categoria_nombre)
                    .addComponent(lblAgregar_categoria_descripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtAgregar_categoria_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtAgregar_categoria_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAgregar_categoria_agregar)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAgregar_categoria)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblAgregar_categoria)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgregar_categoria_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgregar_categoria_nombre))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAgregar_categoria_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgregar_categoria_descripcion))
                .addGap(37, 37, 37)
                .addComponent(btnAgregar_categoria_agregar)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregar_categoria_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_categoria_agregarActionPerformed
        // Capturar la informacion de texto
        String nombreCategoria = txtAgregar_categoria_nombre.getText();
        String descripcionCategoria = txtAgregar_categoria_descripcion.getText();

        // Verificar si tanto el nombre como la descripcions
        if (nombreCategoria.isEmpty() || descripcionCategoria.isEmpty()) {
            // Si alguno de los campos esta vacío, mostrar un mensaje de error y salir del método
            JOptionPane.showMessageDialog(null, "Debe ingresar tanto el nombre como la descripcion de la categoria.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear un objeto Categorias con la información capturada
        Categorias nuevaCategoria = new Categorias();
        nuevaCategoria.setNombre_categoria(nombreCategoria);
        nuevaCategoria.setDescripcion(descripcionCategoria);

        // Llamar al metodo insertar del DAO para guardar la nueva categoría
        boolean insertado = daoCategorias.insertar(nuevaCategoria);

        if (insertado) {
            // Limpiar los campos de texto después de insertar
            txtAgregar_categoria_nombre.setText("");
            txtAgregar_categoria_descripcion.setText("");
            // Mstrar un mensaje de éxito al usuario
            JOptionPane.showMessageDialog(null, "Categoria agregada correctamente.");
        } else {
            // Si ocurrio un error mostrar un mensaje de error al usuario
            JOptionPane.showMessageDialog(null, "Error al insertar la categoria.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregar_categoria_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vAgregarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vAgregarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vAgregarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vAgregarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vAgregarCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar_categoria_agregar;
    private javax.swing.JLabel lblAgregar_categoria;
    private javax.swing.JLabel lblAgregar_categoria_descripcion;
    private javax.swing.JLabel lblAgregar_categoria_nombre;
    private javax.swing.JTextField txtAgregar_categoria_descripcion;
    private javax.swing.JTextField txtAgregar_categoria_nombre;
    // End of variables declaration//GEN-END:variables
}
